### ISSUE TITLE
Epub reader controls

### ISSUE THREAD

**Issue by aaronleopold** [stumpapp/stump#114]
Basic *non-streaming* epub reading are supported on the client, but the current UI for the controls while reading EPUB files leaves LOTS to be desired.

In general, the current implementation needs to be redesigned with MUCH better UX and functionally extended to allow basic config options:

- [x] increasing/decreasing font size, allow for input as well
- [ ] update theme
- [x] read direction (e.g. right to left)
- [ ] search in page?

I've kind of been soft-inspired by Apple's book app, but not completely in-love with it:

![Image](https://user-images.githubusercontent.com/36278431/230794139-304b4683-76cb-42a0-9064-dce53759c646.png)

**Comment by MartenBE** [comment]
If possible, it would be nice to have a way to quickly reach a certain page in large books (e.g. page 589 in a book of 963 pages)

**Comment by aaronleopold** [comment]
> If possible, it would be nice to have a way to quickly reach a certain page in large books (e.g. page 589 in a book of 963 pages)

This _might_ be possible with the epub.js reader (i.e. what is currently in Stump today), but I'd have to investigate a bit more. The caveat with this sort of thing for epub files is that they are essentially just a collection of HTML and CSS, and pages are somewhat artificial and completely dependent on the viewport size. For example when viewing on my laptop full screen there might be 963 pages, but reading on my phone, or perhaps just changing the size of my browser on the laptop or even the font size to something huge, it might report 1700 pages total. This also adds a little bit to the client-side operations (i.e. calculating these numbers).

Either way, I think it is a good feature and worth looking into at least! So, feel free to create a separate issue if you'd like to track it individually 🙂
