### ISSUE TITLE
[FEATURE] Previous/Next page keyboard shortcuts

### ISSUE THREAD

**Issue by omnisci3nce** [stumpapp/stump#123]
Being able to hit the left/right arrow keys or pageup pagedown keys to change pages in the EPUB reader would be nice

_Bonus points would be being able to list keyboard shortcuts somewhere for when you forget them (press `?` to open a shortcuts reminder?)_

**Comment by omnisci3nce** [comment]
Scope on this one seems like it's reasonably small (excluding the Bonus points section which is really its own Issue) so I can have a go at this if you want.

**Comment by aaronleopold** [comment]
Yeah the scope is relatively small, you're more than welcome to take a stab at it if you’d like!

**Comment by JMicheli** [comment]
It seems like there hasn't been much movement on this issue, so I took a cut at it as a way of familiarizing myself with the repo (I love a Rust project). I will submit a pull request shortly.

**Comment by aaronleopold** [comment]
Awesome, thanks! Keep [this comment](https://github.com/stumpapp/stump/issues/179#issuecomment-1773264561) in mind when you dig into that part of the code

**Comment by omnisci3nce** [comment]
Yeah sorry I got pretty busy after commenting. I forked and made something that sort of worked but ran into some edge cases working with epub.js (because it gets focused) if I recall correctly and then got sidetracked by other stuff. Glad that you're picking it up tho!

**Comment by aaronleopold** [comment]
Added in https://github.com/stumpapp/stump/pull/182
