### ISSUE TITLE
[FEATURE] Upload From Web UI

### ISSUE THREAD

**Issue by hay-kot** [stumpapp/stump#133]
**Is your feature request related to a problem? Please describe.**

My workflow for books is to download them onto my computer or phone directly. Instead of moving them via FTP, I'd like to just upload them to stump directly. 

**Describe the solution you'd like**

Stump should allow for uploading an e-book directly on the webpage. 

**Describe alternatives you've considered**

Using FPT or other 3rd party file transfer

**Additional context**

Happy to make a PR for this one if accepted.

**Comment by aaronleopold** [comment]
Hello again 😄 !

I'm not opposed to this kind of functionality living in Stump, either, but I think there are some things that would need to be thoroughly worked out beforehand. Additionally, as I mentioned in your other issue, I personally won't have development time to give to this until after the core features for the `0.1.0`, but am happy to lend a hand as needed!

A few in the Discord saw this issue and had a brief discussion that at least helped me come up with a couple thoughts that will need addressing/planning:

- Security would be one of my bigger concerns here, as an API that accepts file uploads and places them directly onto my home server, without any sort of checking/scanning, is obviously a much greater risk to me and my network than one that doesn't. I'd want to make sure it is airtight 🔒 
- People have very specific ways of organizing their libraries, and when mixed with Stump's concepts of `Collection` vs `Series` based library structures, it is a little fuzzy as to what the final, resolved path of an uploaded file would be (see [docs](https://www.stumpapp.dev/guides/libraries#library-patterns) for those two aforementioned patterns).
    - There can be some sort of `enter parent directory` input that goes and creates all the directories (as needed) and then places the file there?
    - This can be a feature tied to https://github.com/aaronleopold/stump/issues/40? As that resembles a file explorer (e.g. `create folder`, `upload to folder`, etc.
- RBAC would also need to be considered here, I think at least for the very beginning I wouldn't even want this to be available outside the server owner.

Let me know if you have any thoughts!

**Comment by Guscal** [comment]
im not sure im following this correctyly but i had another idea that maybe relates to this one, is to have abnother profile apart from admin and user that  maybe something called mod, that lets the user upload a book to acertain library, at this moment we are using stump with my friends to share comics and books we are reading and think the others would like, bbut im the one that has upload them to the server, dont know if this is in the roadmap but i think it would ne a neat feature. dont know how problematic it could be

**Comment by aaronleopold** [comment]
> im not sure im following this correctyly but i had another idea that maybe relates to this one, is to have another profile apart from admin and user,  maybe something called mod, that lets the user upload a book to acertain library, at this moment we are using stump with my friends to share comics and books we are reading and think the others would like, bbut im the one that has upload them to the server, dont know if this is in the roadmap but i think it would ne a neat feature. dont know how problematic it could be

Yeah that sounds pretty much on the nail for what functionality this issue asks for. Most of my previous response is just me vomiting some thoughts about how certain aspects would have to work and also pointing out the potential risk of allowing arbitrary file uploads from a client to your remote server. I think the last point I make there about RBAC is more what you’re asking. 

Right now in Stump there is very minimal user management/access control. Ideally, a server owner could assign multiple roles to a user that grants them access to something, e.g `file_uploader`, `file_downloader`, etc. This sort of thing is on the roadmap, and I’ve implemented good RBAC systems for a couple other areas (reading lists) i plan to use as a base, but this touches all areas of the API so would be a bigger chunk of time. After I wrap up the current stuff I’m implementing, I can see about starting to flesh out RBAC. Getting this system out the door will better enable book clubs, which is one of my favorite features I’ve thought of TBH.

**Comment by paulcsiki** [comment]
Also interested in this feature. It doesn't have to be very fancy, server admins can secure it on their own.

**Comment by aaronleopold** [comment]
This was implemented as part of #492 and has landed in the `experimental` image as of yesterday evening. I am closing this as completed
