### ISSUE TITLE
[FEATURE] abilty to set thumnails by selecting from current page 

### ISSUE THREAD

**Issue by Guscal** [stumpapp/stump#166]
so as the title says, a feature in the web reader to make the current page the thumnail of the series or the current issue/vol/chapter

**Comment by aaronleopold** [comment]
This was actually fairly straight forward to implement on the server, and I'm working through adding the UI hookups now for it. I wanted to caveat by mentioning it won't be fully ideal for this first pass, in that I'm not storing this anywhere (e.g. creating an entry that states for X media or series, I want Y page from Z media for the thumbnail). Rather, I am just one-off generating a thumbnail. This shouldn't be overly noticeable or a hindrance unless you alter your thumbnail config at a higher level (e.g. library) and regenerate thumbnails. At that point, it would overwrite you previous selection. 

In the future, I'll be sure to refactor this to better support that scenario 👍

**Comment by Guscal** [comment]
wow taht was fast! haha amazing thanks for the dedication

**Comment by aaronleopold** [comment]
Closed by https://github.com/stumpapp/stump/pull/167
