### ISSUE TITLE
Refactor parallel scan end logic

### ISSUE THREAD

**Issue by aaronleopold** [stumpapp/stump#169]
The [parallel scanner](https://github.com/stumpapp/stump/blob/develop/core/src/filesystem/scanner/batch_scanner.rs) (to be renamed Quick scanner) is more efficient and speedy than the in-order scanner (to be renamed Default scanner TBD). However, at the very end of the scan it gets out of the parallelism pattern and becomes a bit of a slow hog. 

It needs to be refactored to parallelize and batch at the end, as to cut down on memory usage and increase the speed.

**Comment by DieselTech** [comment]
To go with that, clear indication that it's done with the scanning and moved into the processing phase. That way it doesn't look like it's stuck in a phase.

**Comment by aaronleopold** [comment]
Closing after our discussion on Discord (removing the separation of scanners for the time being)
