### ISSUE TITLE
Consider if migrating to `tower-sessions` is appropriate

### ISSUE THREAD

**Issue by maxcountryman** [stumpapp/stump#173]
Hi folks,

I'm the author of axum-sessions, which is a crate I see you all are using--I'm glad to see you've found it useful!

Over the course of the last year or so we've hit some roadblocks with our key dependency, async-session. The long and short of that is in order to unblock that and address some problems with axum-sessions's design, we've released a new crate which aims to replace axum-sessions: [tower-sessions](https://github.com/maxcountryman/tower-sessions).

tower-sessions no longer relies on a third-party crate for its session implementation and this has allowed us to change its design to better fit tower and the broader tower ecosystem (i.e. axum). For instance, we no longer need writable and readable sessions, and have simplified the interface as a result.

I'd be curious if there's interest in migrating and am happy to help if so.

**Comment by aaronleopold** [comment]
Hey @maxcountryman,

Coincidentally, I migrated to `tower-sessions` just a [couple days ago](https://github.com/stumpapp/stump/pull/171) 😄 I have some error handling improvements to eventually get to regarding the custom store I am using, but otherwise the change was rather seamless. 

> For instance, we no longer need writable and readable sessions, and have simplified the interface as a result.

One of the first things I noticed - thanks for your work!

**Comment by maxcountryman** [comment]
Amazing! I should have looked more closely. Should you have any feedback or feature requests, please do reach out.

**Comment by aaronleopold** [comment]
Nah you're good, it isn't in main yet so easy to miss.

>  Should you have any feedback or feature requests, please do reach out.

Will do, thanks!
