### ISSUE TITLE
[FEATURE] Image analysis job

### ISSUE THREAD

**Issue by aaronleopold** [stumpapp/stump#181]
Add a new job that analyzes archive, image-based media to determine the image dimensions for each page. This is separate from the scanner so it can be opt-in if you want the functionality. 

- Analysis should write media metadata `pages` field with result
- If the media already has `pages` metadata set, validate with the new result
	- Potentially in the future support writing the XML directly

See [Discord request](https://discord.com/channels/972593831172272148/972595078554079232/1166154192520491059) for full context of this request

**Comment by JMicheli** [comment]
What else needs to be done in order to close this issue? I'd like to see closing this and #181 through.

**Comment by aaronleopold** [comment]
> What else needs to be done in order to close this issue? I'd like to see closing this and #180 through.

I actually think both can be closed out! I'll double check tomorrow though, in case I'm missing something, and can close them out afterwards

**Comment by aaronleopold** [comment]
Implemented by https://github.com/stumpapp/stump/pull/307
