### ISSUE TITLE
[BUG] can't go to the last page with right arrow key

### ISSUE THREAD

**Issue by iwa** [stumpapp/stump#203]
**Describe the bug**
I often read with the arrows keys as i find it easier to change pages, but i found out that when you're viewing the before-last page, you can't use the right arrow key, it just does nothing

**To Reproduce**

1. Open a book
2. Go to the page before the last page
3. Try to use right arrow key
4. See that nothing happens, you have to use your mouse

**Expected behavior**
Should go to the last page as intended

**Screenshots**
n/a

**Desktop (please complete the following information):**

- OS: Windows, using Brave

**Comment by aaronleopold** [comment]
Hey 👋 thanks for reporting this! Looks like it is a super quick fix, so I'll try and knock it out after work today but definitely over the weekend otherwise

**Comment by aaronleopold** [comment]
The updated nightly went out yesterday, it should be fixed now! If you still encounter the issue though let me know, otherwise I'll close this as completed

**Comment by iwa** [comment]
can confirm it works fine with the latest build, thanks for your quick fix!
