### ISSUE TITLE
[FEATURE] Button to set as read

### ISSUE THREAD

**Issue by iwa** [stumpapp/stump#204]
**Is your feature request related to a problem? Please describe.**
You have to read the entire book to have it considered as read

**Describe the solution you'd like**
A simple button on the book page to set the book as read

**Comment by jacobkossman** [comment]
I think a minor addition to this would be to mark as unread (so make this a toggle)

**Comment by aaronleopold** [comment]
This was added as part of #208, and will be live once the next [nightly build completes](https://github.com/stumpapp/stump/actions/runs/7108960572). Thanks for the suggestion!
