### ISSUE TITLE
Sidebar lacks colos in light mode

### ISSUE THREAD

**Issue by anddam** [stumpapp/stump#220]
**Describe the bug**
Using Stump in an iframe with dark background, the `aside:first-child div` element does not have a background color set, resulting in `rgba(0,0,0,0)` and in black font text displayed onto the dark background.

**To Reproduce**
1. Put stump into an iframe with a dark background.
2. Observe the text is not readable like in this screenshot:

![Screenshot 2023-12-11 135336](https://github.com/stumpapp/stump/assets/689872/1f1f625e-237a-4571-aafb-ab0151aa66f4)

**Expected behavior**
The text should be readable in light mode as it is in dark mode, where font color and background have contrast.

I suggest you assign a white background to the `div` element contained in `aside`.

**Comment by anddam** [comment]
Thanks.

Sure thing, I'll add styling glitches here if I catch any other.

**Comment by aaronleopold** [comment]
This should be fixed in the latest nightly now 👍
