### ISSUE TITLE
[BUG] Black text on black background, epub on dark theme

### ISSUE THREAD

**Issue by TheRouce** [stumpapp/stump#243]
**Describe the bug**
Black on black when viewing epub with dark theme on

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Appearance'
3. Change theme to 'Dark'
4. View epub

**Expected behavior**
1. white on black text when using a dark theme
2. option to override reader appearance settings

**Screenshots**
![image](https://github.com/stumpapp/stump/assets/40551268/ba357565-c33b-43c2-8d56-1e7e7efb6821)
![image](https://github.com/stumpapp/stump/assets/40551268/81c712ad-7ad9-47ae-a7ce-5597885b6c6d)

I don't know how visible this will be but sometimes flipping between pages I see a blink of white text then it goes black. Not sure if this helps with fixing the bug:
![Peek 2024-01-18 13-16](https://github.com/stumpapp/stump/assets/40551268/82b64ea0-bab7-4317-a627-4fe1d64e39c8)

**Additional context**
I did a quick search of issues and didn't see a related one, let me know if this is related to another issue or report.

**Comment by aaronleopold** [comment]
Hey 👋 

Thanks for reporting this! Are you able to test that this bug presents in other epub files? Or is it just this one? My immediate feeling is that there is some asset/style in the epub that is overriding Stump's, which would explain why you are seeing that flash, as well.

If it does wind up being isolated to that (or a select few) epub files, there are a few ways to continue debugging:

1. If you're able to, send me the file and I can handle figure out where and why
2. Inspect the iframe and send me the selector for any given text element and any style definitions/overrides shown

**Comment by TheRouce** [comment]
The two screenshots are from separate files, seems to only affect a couple.

Here's the second one:
https://annas-archive.org/md5/274524bec378a5069f5e46ff2a146b55

**Comment by aaronleopold** [comment]
This is exactly what I needed, thank you! I was able to reproduce and correct the issue locally with the epub file you linked, I'll be sure to put up a PR this afternoon after work with those changes 👍

**Comment by aaronleopold** [comment]
The latest nightly has this fix, if you're able to try it out and let me know if it resolves the issue on your end

**Comment by TheRouce** [comment]
Works! 
![image](https://github.com/stumpapp/stump/assets/40551268/95a119fe-05cf-49f7-aa76-faa13c19ea8c)
