### ISSUE TITLE
[FEATURE] Endless scroll mode

### ISSUE THREAD

**Issue by Joever9000** [stumpapp/stump#276]
**Is your feature request related to a problem? Please describe.**
No endless scroll reader option

**Describe the solution you'd like**
An option to read with endless scroll (you scroll down through the images, rather than instantly load one image and then the next)

**Comment by aaronleopold** [comment]
I realized this is actually a duplicate of https://github.com/stumpapp/stump/issues/116, but I'll keep this one around instead and close the old one.

**Comment by aaronleopold** [comment]
Will be released in `0.0.2`

**Comment by Joever9000** [comment]
Thanks dude. I hope this isn't the wrong place to put it, but I really appreciate your work, looking forward to the next release!

**Comment by aaronleopold** [comment]
This ticket is closed, but I recently discovered the library I used for the vertical endless scroll mode released [horizontal support](https://virtuoso.dev/horizontal-mode/) somewhat recently 🙌

I'll update the current implementation to include additional options as part of #391
