### ISSUE TITLE
[FEATURE] Scanner ignore rules

### ISSUE THREAD

**Issue by aaronleopold** [stumpapp/stump#284]
**Is your feature request related to a problem? Please describe.**

This supersedes [#53](https://github.com/stumpapp/stump/issues/53)

I don't feel that managing opt-in ignore rules via `.stumpignore` files is the best route to take. One so people don't have a slightly tedious chore if they decide to uninstall Stump, but mostly it just isn't a great management flow IMO.

**Describe the solution you'd like**

Support dumping a set of ignore rules to the DB instead, this can be populated via the UI

**Additional context**

I am unsure if series should have their own ignore rules, and regardless of whether they do if they should inherit the rules from the library. I think, in general, the 'rules' of these rule-sets needs to be thought through and defined a bit.

**Comment by mr-szgz** [comment]
Have you considered a simple ignore list of RegEx strings? or globs? I personally find globs, especially with autocomplete, is quite user-friendly.

For regex, here is an example from another media app I use:
![IMG_0309](https://github.com/user-attachments/assets/cba5c1d2-bbb9-4d30-9057-327c99aa4a2b)

**Comment by aaronleopold** [comment]
Hey! 👋 what you described is already planned. Previously, Stump supported `.stumpignore` files which contained a set of regex strings. This issue aims to replace that with a persisted value in the DB, which can be viewed/managed on the UI

**Comment by aaronleopold** [comment]
Implemented as of https://github.com/stumpapp/stump/pull/422, tentatively to be released in `0.0.7`
