### ISSUE TITLE
[TRACKING] Build native binaries during release

### ISSUE THREAD

**Issue by aaronleopold** [stumpapp/stump#310]
An issue to capture the ask for building native binaries during release. The following platforms are planned to be supported:

- [x] Linux (x86_64)
- [x] macOS (x86_64, arm64)
- [x] Windows (x86_64)

## Additional context

There are a few actions which have already been defined that just need testing and refining. The following are relevant:

- [`build-server`](https://github.com/stumpapp/stump/blob/main/.github/actions/build-server/action.yml)
- [`build-web`](https://github.com/stumpapp/stump/blob/main/.github/actions/build-web/action.yml)

Realistically, caching needs to be implemented to speed up the build process before I would want to include this in the release process.

**Comment by JMicheli** [comment]
I'd be open to taking this on. I enjoy tooling-related tasks and this doesn't sound too difficult.

**Comment by aaronleopold** [comment]
> I'd be open to taking this on

If you need anything give me a shout ❤️

I think besides from the caching I mentioned in the issue description, which I am OK omitting for the time being, the main consideration would be the timing for when the binaries are built. Currently, the docker build gets kicked off in a very specific scenario (a branch which matches the `release/v` pattern is merged to main). However, binaries would be attached to a tag, which up to this point has been created manually by me.

So I guess the question(s) phrased more concretely would be:

1. When should the binaries be built?
2. How should the binaries be attached to a tag?
3. Should the current release workflow be adjusted or do we create a separate one?

**Comment by aaronleopold** [comment]
Resolved by https://github.com/stumpapp/stump/pull/369 and https://github.com/stumpapp/stump/pull/374
