### ISSUE TITLE
[BUG] Forward-Backward swipes pages in opposite direction

### ISSUE THREAD

**Issue by adityatelange** [stumpapp/stump#323]
**Describe the bug**
Swiping action on mobile devices/smaller screens is reversed. Swiping from left to right, moves to next pages while swiping from  right to left moves to previous pages.

**To Reproduce**

1. Open Stump in a mobile browser.
2. Open a book and swipe pages.

**Expected behavior**
Swiping from left to right, should move backwards while swiping from right to left moves forward in book.

**Screenshots**

https://github.com/stumpapp/stump/assets/21258296/4fa6948a-ff36-4358-80d3-4e1adda90d10

**Desktop (please complete the following information):**

- OS: NA

**Smartphone (please complete the following information):**

- Device: Any mobile device.
- OS: Android

**Additional context**

**Comment by aaronleopold** [comment]
Hey 👋 thanks for reporting this. For some reason I am unable to play the example video you provided. Is this issue presenting in the image-based reader or the EPUB reader?

**Comment by adityatelange** [comment]
> Hey 👋 thanks for reporting this. For some reason I am unable to play the example video you provided. Is this issue presenting in the image-based reader or the EPUB reader?

Hi! This is with epub-reader https://website/books/<id>/epub-reader?stream=false

**Comment by aaronleopold** [comment]
Thank you! Can you just confirm the reading direction for me? I assume you are wanting to use LTR based on the original description of the issue, so if it is set to LTR my guess is the logic was flipped by mistake. 

I won't be home to take a look for a bit, but I'll aim to get a fix in before the weekend is over at least.

**Comment by adityatelange** [comment]
Can you access the video over here? https://www.youtube.com/watch?v=yFcxJ5W_StA

**Comment by aaronleopold** [comment]
> Can you access the video over here? https://www.youtube.com/watch?v=yFcxJ5W_StA

Yep! I can see that, thank you. It does look like it's just opposite what it should be, I'll drop another comment here once a fix is in the nightly image

**Comment by aaronleopold** [comment]
The fix should now be in the latest `nightly` image. I'll close this issue out, but feel free to re-open it if the problem persists

**Comment by adityatelange** [comment]
@aaronleopold thanks for fixing this so fast 😃 really appreciate it!
