### ISSUE TITLE
Basic PDF support

### ISSUE THREAD

**Issue by aaronleopold** [stumpapp/stump#35]
The server needs to be able to: process, properly handle and serve PDF files. This issue is for *basic* support, _page streaming_ support will either roll out separately or, depending on how the rest of the below goes, at the same time. 
 
Core Tasks:
- [x] Add logic to detect PDF mime
- [x] Add logic for PDF operations:
    - [x] Simple file serving
    - [x] Thumbnail extraction and/or generation
    - [x] Metadata extraction / interpretation
- [x] Start accepting PDF files during scan

Interface Tasks:
- [x] PDF Reader (via file serving)
- [x] Streamable PDF reader

**Comment by berkingurcan** [comment]
I can take this.

**Comment by aaronleopold** [comment]
Sure thing, just assigned you. Thanks!

**Comment by aaronleopold** [comment]
I think this is promising: https://github.com/ajrcarey/pdfium-render

Depending on how fast of an operation it is to convert a PDF page to a bitmap, that could potentially work for streaming PDF pages. However, that library would easily allow for converting PDF to archive formats I think (also very great). Static compilation might be tricky, but there is an entire section for that in their README

**Comment by KrautByte** [comment]
Agreed, I would like to create a general design spec for this first though, making sure every file format has the same methods so interfacing and documentation become easier if that makes sense.

**Comment by aaronleopold** [comment]
Sounds good!

**Comment by aaronleopold** [comment]
Mostly completed this today 🎊 per-page streaming as well as the option to use your browser's native PDF viewer are both available now.

The only thing left at this point is to update the Dockerfile to pull in the PDF dependency.

**Comment by aaronleopold** [comment]
Resolved by https://github.com/stumpapp/stump/pull/158. I am deploying updated docs to reflect PDF support, but should eventually make a note about PDFium being used
