### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by jayjoshi64** [stumpapp/stump#356]
**Describe the bug**
Opening links on a new browser instance fails with 

```
Cannot read properties of undefined (reading 'includes')
```

The error persists even after I remove the sub-path.  (/books/<ID>)

**To Reproduce**

1. Open a book and copy its link. 
2. (I personally book marked it through an app)
3. Open the link in a different browser, OR, open the link in incognito session.
4. The error will appear

**Expected behavior**
If the browser session is not found, the app should open the login page.  It should not error out. 

**Screenshots**
<img width="706" alt="image" src="https://github.com/stumpapp/stump/assets/20963493/ecde3c1a-175f-499b-9a9a-f40e6d103851">

**Desktop (please complete the following information):**

- OS:  macOS with Linux server

**Additional context**
Btw,  "Copy Error Details" button is also not working.

**Comment by aaronleopold** [comment]
Resolved by #358
