### ISSUE TITLE
Panic/Seg Faulting with Rar files

### ISSUE THREAD

**Issue by aaronleopold** [stumpapp/stump#38]
After some helpful testing from people in discord, this nasty little bug was found. It seems to only present when running Stump in Docker, which is super annoying lol. I've narrowed it down to when I try and extract the byte content of a file within the rar archive without unpacking it.

I think a potential work around might be to not use the unrar library in Docker? Or to try and rework the `read_bytes` work around I wrote (as it isn't wonderful)

![Image](https://user-images.githubusercontent.com/36278431/184459693-2fc5de28-7fe7-4ecf-bffd-2ba7373deb86.png)

**Comment by aaronleopold** [comment]
See https://github.com/aaronleopold/stump/pull/138 for update

**Comment by MartenBE** [comment]
This isue is probably the cause of the following output in the doker logs?

```
stump-stump-1  |   2023-07-09T13:22:56.423830Z ERROR stump_core::filesystem::scanner::utils: Error occurred trying to build media entity, build_result: Err(InternalError("Unsupported file type: Stump cannot currently support RAR files in Docker."))
```

Otherwise great piece of software!

**Comment by aaronleopold** [comment]
> This isue is probably the cause of the following output in the docker logs?
> 
> 
> 
> ```
> 
> stump-stump-1  |   2023-07-09T13:22:56.423830Z ERROR stump_core::filesystem::scanner::utils: Error occurred trying to build media entity, build_result: Err(InternalError("Unsupported file type: Stump cannot currently support RAR files in Docker."))
> 
> ```
> 
> 
> 
> Otherwise great piece of software!

Yep! That’s the reason, unfortunately. Version 0.5 of the unrar crate I use was released the very end of June, and it seemed to still have the issue. I plan on creating a reproduction with a much smaller Axum server to try and get to the root of the problem.

**Comment by aaronleopold** [comment]
This should _hopefully_ be resolved with https://github.com/stumpapp/stump/pull/150. Testing locally when using a Debian base image, instead of Alpine I didn't experience any seg fault. An `experimental` tag will be pushed to dockerhub with the Debian base, and then after some testing I'll consider this issue resolved if all goes well

**Comment by MartenBE** [comment]
It seems to work at first sight. Thanks, I am now trying to use it as my main book/comic server :) !
