### ISSUE TITLE
[FEATURE] Distinguish reading preferences between mangas and comic books (left vs right). 

### ISSUE THREAD

**Issue by hollisticated-horse** [stumpapp/stump#384]
**Is your feature request related to a problem? Please describe.**

Being able to distinguish defaults for mangas and comic books. Both are in CBZ/CBR format, but they are not read in the same direction. 

**Describe the solution you'd like**
So I'd like to be able to set those parameters for a specific library (manga vs comic).

Modifies: 

- reading direction 
- if double spread, make sure that the correct image is displayed left and right
- maybe add some ui design nudge to help along a user to remember to go in the right direction if unfamiliar
    - progress bar going left or right ? 

**Describe alternatives you've considered**
Kavita tries to do this, and I'll go into details later why it doesn't work imo. 

**Additional context**
Probably either a user preference, with a default that the admin can set server wide or
admin preference only.

**Comment by aaronleopold** [comment]
I like this! 👍

Wanted to quickly touch on:

> if double spread, make sure that the correct image is displayed left and right

This actually isn't even supported now. I don't think it is a huge task, but since you called it out just wanted to make that note.

You're welcome to create a secondary issue if you want to track it individually

**Comment by hollisticated-horse** [comment]
> This actually isn't even supported now. I don't think it is a huge task, but since you called it out just wanted to make that note.
> 
> You're welcome to create a secondary issue if you want to track it individually

Which one do you mean ? The double spread or being able to define which page goes left and right ?

**Comment by aaronleopold** [comment]
> Which one do you mean ? The double spread or being able to define which page goes left and right ?

Both, since one precludes the other. The readers in Stump don't yet support a two-page layout, and since that itself isn't yet implemented there also is no way to change that ordering.

Though, how common is it that you find yourself needing to reorder a double spread? The configured reading direction is all that I can imagine mattering wrt ensuring a double spread is ordered properly (but also all the pages, at that point 😅)

**Comment by hollisticated-horse** [comment]
> Both, since one precludes the other. The readers in Stump don't yet support a two-page layout, and since that itself isn't yet implemented there also is no way to change that ordering.

I'm assuming you mean the custom pdf/cbz/cbr reader you implemented ? 
I'll open an issue for that :D and will mention the 

> Though, how common is it that you find yourself needing to reorder a double spread? The configured reading direction is all that I can imagine mattering wrt ensuring a double spread is ordered properly (but also all the pages, at that point 😅)

Excellent question. Maybe I mispoke. I was talking about the fact that manga double spread (left <- right) is different from comic books (right-> left) and that the reader software might need to infer which pages correctly forme a double spread in both cases. That could be set per library. 

I believe that the amazing [https://killsixbilliondemons.com/](https://killsixbilliondemons.com/) is a great example of a comic that has needs double spreads, but then I believe taht the double spreads are jus one big horizontal page... Might need to account for that took I think. 

For mangas, I'm might need to dig a little bit for a good example. 

Either way, you are probably right in saying that stump doesn't need to reorder pages.

**Comment by smldub** [comment]
> For mangas, I might need to dig a little bit for a good example.

Here is an example (it is from Berserk, which is graphic so I edited these photos), with some dirty edits to the pagedreader you can get it to spit out two pages either in inverted side by side or in the normal way. 

# normal way 
![bad_edit](https://github.com/user-attachments/assets/3d51f343-2f4d-4279-b091-9532bea27912)

# inverted way (for mangas)
![good_edit](https://github.com/user-attachments/assets/2647f69b-4dcd-4d6c-abfd-5684342888c8)

It can have a pretty big effect on the resulting composite image

**Comment by hollisticated-horse** [comment]
yup, definitly nsfw @smldub XD

**Comment by aaronleopold** [comment]
See https://github.com/stumpapp/stump/issues/391#issuecomment-2336458021 for update
