### ISSUE TITLE
[FEATURE] PDF/CBZ/CBR custom reader display double spread pages

### ISSUE THREAD

**Issue by hollisticated-horse** [stumpapp/stump#391]
**Is your feature request related to a problem? Please describe.**
The pdf/cbr/cbz reader doesn't have an option to display in double spread, or two pages side by side. Mentioned in #384 

**Describe the solution you'd like**
- Add an option somewhere to have double spreads
- also define the read direction, left ← right for manga or right → left for western comics. 
     - the pages view at the bottom might need to mirror this, by scrolling in the right direction.
- add subtil hint of the read direction for people not used to reading certain mediums. Could be a dark to light gradient in the background, or a border color ? Needs designing.  
- add an option to set the read direction per library, if you organize per medium. 

**Describe alternatives you've considered**
n.a.
maybe just having the admin options and not let the users choose ? 

**Additional context**
kavita sort of has this, but it never worked well...

**Comment by aaronleopold** [comment]
I've officially started working on this feature. So far, the behavior will be as follows:

- You may configure default settings for the reader(s) as part of library settings. Any book without overrides will default to these settings
- You can override settings on a per-book basis when you are in a reader (via the toolbar). The overrides are persisted to your client only, they are not synced to the DB
    - There will be options in settings to clear any local configurations
- The initial set of options which may be configured will be:
    - Double spread (has no effect on continuous scrolling)
    - Reading direction (ltr or rtl, also has no effect on continuous scrolling)
    - Image height/width sizing (see #437)
- If a user doesn't like these settings, they currently have to override them for each book. I haven't come up with a solution for this yet, and might punt it to after the initial effort

I'm focused on the functionality for now, as it will be a solid chunk of work. I can post an update with what it looks once it is properly designed. If you (or any onlookers) have thoughts, feel free to share

**Comment by aaronleopold** [comment]
<details>

<summary>Tentative designs</summary>

<img width="1624" alt="Screenshot 2024-09-10 at 6 08 50 PM" src="https://github.com/user-attachments/assets/03f3df0a-d1ad-4e56-b30e-15a80491e497">
<img width="1624" alt="Screenshot 2024-09-10 at 6 08 29 PM" src="https://github.com/user-attachments/assets/73d537ad-20df-45d9-a735-aca6bfc26bcf">
<img width="1624" alt="Screenshot 2024-09-10 at 6 08 21 PM" src="https://github.com/user-attachments/assets/156af413-3320-4291-92b1-82b089ac9f13">


</details>

**Comment by hollisticated-horse** [comment]
Nice !!

I think I would expect the preview to highlight both displayed pages, not just the first one. 



<img width="377" alt="stump_double_spread_closeup" src="https://github.com/user-attachments/assets/615e3715-ffa8-47e4-940d-b69bca69e16c">

**Comment by aaronleopold** [comment]
> I think I would expect the preview to highlight both displayed pages, not just the first one. 

Yeah I agree, I'll try to find time to squeeze that in but it might wind up being a follow-up


> Other suggestion, have the current active pages in the center, even at the start of the document ?

I can consider it, but implementation would be more complex to get something functional with the virtualizer. As the above, it would likely be after though

**Comment by hollisticated-horse** [comment]
Yup, no worries. Just making suggestions.
