### ISSUE TITLE
[FEATURE] Any plan to implement Mobi ?

### ISSUE THREAD

**Issue by GregTroar** [stumpapp/stump#410]
Hello,

Is there any plan to implement Mobi management ?

Thanks

**Comment by aaronleopold** [comment]
Hey 👋 

There are no plans at the moment. 

I'm happy to look into what would be involved and how feasible it might be when I have some free time in the next week or so

**Comment by DieselTech** [comment]
Mobi is a dead format that was killed off when Amazon bought the company out in the early 2000's. At this point you would be better off converting your mobi files to epub using something like calibre

**Comment by GregTroar** [comment]
Thanks for reply, definitely not critical at all if the format is dead.
I will convert to epub

**Comment by aaronleopold** [comment]
> Mobi is a dead format that was killed off when Amazon bought the company out in the early 2000's. At this point you would be better off converting your mobi files to epub using something like calibre

Yeah so I did a little digging just to learn more, and @DieselTech is correct. The only reason someone might have wanted to use `mobi` was for Kindle compatibility from what I can tell, but Kindles now support EPUB files so there is little reason not to convert to the better format. Especially considering EPUB has broader compatibility and there are multiple tools available online for converting them.

For the sake of convenience on your end, I did spend a little time investigating what the effort might be for supporting the format in the code. It is relatively small effort to support the format for the purpose of scanning and serving to a client. The problem would be that the effort to support reading them using a built-in reader is large, and not something I want to commit to at the moment for a dead format.

I'm going to close this request as "won't fix" for now, but if you have a very specific use case that requires `mobi` support and you absolutely cannot convert to EPUB, please let me know and I can reconsider at least the scanning and file serving aspect.

I also would encourage anyone else who might be interested in this feature to consider contributing to the project. I would be happy to help guide you through the process of adding support for the format in the core, as it is primarily developing another specialized file processor using something like this [crate](https://docs.rs/mobi/latest/mobi/)
