### ISSUE TITLE
[BUG] Image scaling makes long strip comics unreadable

### ISSUE THREAD

**Issue by retmas-gh** [stumpapp/stump#437]
**Describe the bug**
The bug varies by device type / reader mode:
- on desktop in both continuous and paged mode each image ("page") is scaled to the visual height of the browser, which makes each image smaller in width the longer it is
- on mobile in continuous mode the bug looks like on the desktop version
- on mobile in paged mode each page image is stretched to the view, so the longer the image, the more squashed it is

**To Reproduce**

1. Add a long strip comic to the application
2. Open the comic on an affected device
3. Go to the long strip page and witness the beforementioned behavior

**Expected behavior**
Readable long strips

**Screenshots**
![example](https://github.com/user-attachments/assets/7985c868-e37c-449c-8f86-d9219adebc5d)
(I pixelized the images a bit but it's still visible I hope; the left shows desktop browser with raw images of same width [you can see the dimensions of the pictures on two opened tabs] and the right is the squashed mobile paged mode view)

**OS**
Windows, Linux, iOS, Android

**Additional context**
To specify I encounter this while reading manhwa/manhua which are almost exclusively long stripped. I'm not sure if there are other popular media types which use such form (and if continuous mode was even made with this purpose in mind).

Not sure what the best approach would be, but since long strip comics are propably only read with continuous mode, making it so images in that view are scaled to the device width with height on auto on mobile and some sensible value for max width (there is a grayed out viewport option in appearance tab for this i guess?) on desktop I think would be the best solution.

**Comment by aaronleopold** [comment]
Hey thanks for reporting this! I'm not familiar with long strip comics, are they generally one long page or several long pages? Regardless, I think your suggestion is reasonable:

> [images] are scaled to the device width with height on auto on mobile and some sensible value for max width...on desktop

The one issue is that I think this generally clashes with how normal comics should be presented, and there is no way realistically to infer which is preferred at the time of readings. There might be some programmatic way of deducing based on the image dimensions, but then you run the risk of the app choosing incorrectly.

Would it be an acceptable solution to have some sort of manual toggle / adjustment / preference for the respective height and width scaling? Or a more preset-like button? I'm thinking either:

1. Toggle for long strip vs normal comic
2. Explicit settings to control the width and height (full, auto)

I'll likely fix this bug alongside [#391](https://github.com/stumpapp/stump/issues/391), as I've already started it and don't want to juggle too many conflicts come merge time 😅

**Comment by retmas-gh** [comment]
Hi.

As I mentioned earlier, I only encountered such type of comics with manhwa and manhua (which are korean and chinese comics respectively).
I understand that your primary goal for this project is rather western comics oriented but I do love this app estheticity and simplicity (at least in these early stages) so it would be nice to get these working properly too.

Regarding the format, these long strip comic images are of various lengths but of the same width (that's why, as pictured on the reader in continuous mode on the desktop, the first image which is longer is thinner than the second one).

As for a solution: I personally divided my collection by manga/manhwa/manhua/others, so maybe a nice approach, if possible, would be a library wide toggle for long strip comics so you would not need to switch manually every time?

Thanks for considering this at all :)

**Comment by aaronleopold** [comment]
> I do love this app estheticity and simplicity (at least in these early stages)

Happy you like it! 

> Regarding the format, these long strip comic images are of various lengths but of the same width (that's why, as pictured on the reader in continuous mode on the desktop, the first image which is longer is thinner than the second one).

Got it, thanks for clarifying. I appreciate it!

> if possible, would be a library wide toggle for long strip comics so you would not need to switch manually every time?

Yeah for sure. As part of the aforementioned (aforelinked?) issue I am adding library defaults, e.g. reading direction, double spread, reading mode (paged vs continuous) etc. I can add default options for the height and width too, which means I'll likely try to go for the second option I outlined above:

> Explicit settings to control the width and height (full, auto)

My thoughts so far wrt these settings are if you change these settings while reading a book (e.g. using the toolbar in a reader) it will apply to that book only. The library settings will eventually get its own sections for these defaults. I'll be sure to link this issue once a PR is made, hopefully within the next few weeks

**Comment by aaronleopold** [comment]
I threw together a WIP implementation during my lunch today, it's a little rough but wanted to share in case you (or anyone else) has any thoughts.

The main "issue" is that different viewport sizes will have different results when messing with these settings. I didn't really have a lot of time to think through the full behavior, but this is what I currently have: https://github.com/stumpapp/stump/commit/880ad2e7061aae6a94d8cc96b20ab5c6b7f5da27#diff-52f877962cb3a30d4b8a117df8f80526d2ccb38a886d9912b6663cac3e9deac7R106-R113

Also while re-watching the demo, the  `fill` variant for height is wrong haha but I'll fix it eventually

<details>

<summary>Demo</summary>

https://github.com/user-attachments/assets/2b1c11e5-f00a-45ed-862a-d5917b09abfc

</details>

**Comment by retmas-gh** [comment]
Sorry for the late respose, didn't think you would start so soon.

To be honest, having an ability to change the scaling at all, leaving the same defaults as they exist today for people who already use the application, is the best thing to do.

Having said that, I don't know if I've ever seen any vertical digital image books so I'm not sure if there is a point to complicate things with width option besides auto? If it's about my screenshot of mobile version, I would think it's still because of the height scaling not width but I may be mistaken.

As I mentioned earlier, having an option (just for the height) of the current scaling (is it 100% vh?) and the fill (to the value of "Adjusted width" option in mentioned appearance tab if it's the container for the images) would be the best option in my opinion.

And, if it's not because of this being WIP, I guess it would be better to have these as a buttons not a list.

PS. Funny that you chose the demo to be in the one scanario that works perfectly for me (pc and paged view). :smile:

**Comment by aaronleopold** [comment]
> Sorry for the late respose, didn't think you would start so soon.

No worries at all! I have no expectations about people's time, life is busy

I think you made some good points, and while I want to respond to each one I actually refactored the work I had already done to be a little more simplistic than having multiple options per dimension. So the previous demo wouldn't really be applicable anymore.

The way I've updated it is effectively being able to prioritize one of the following:

1. Scale to fit the height of the viewport (width is effectively auto)
2. Scale to fit the width of the viewport (height is effectively auto)
3. Don't scale, try to keep original with scrolling as necessary (effectively no scaling)

These work fairly well so far in my testing, but have a few odd behaviors to fix between the reading modes (mostly horizontal scrolling)

> PS. Funny that you chose the demo to be in the one scanario that works perfectly for me (pc and paged view). 😄

Happy I chose well for demoing your use case 😄

**Comment by retmas-gh** [comment]
Hi.
Considering the mentioned draft PR and its description I understand this should be more or less done.
I've managed to compile said PR and wanted to show you my experience with changes regarding this issue.
First, here is a video:

<details><summary>Click me</summary>

https://github.com/user-attachments/assets/5ac2366c-df3b-4d09-a3c1-f44841b00128

</details>

Now, my observations:
- the scaling does work with paged mode (all three)
- on the vertical scroll not much changed from before the PR unfortunately:
  * the images seem to still scale to the visual height...
  * ... but not exactly because the white image seen at the the end has a huge margin (so it fits exactly to the visual height); the original image dimensions are as shown (the white part)
  * the options of image scaling show no difference

Thank you for taking the time to do these things.

**Comment by aaronleopold** [comment]
Hey thank you! This is extremely helpful, I appreciate you taking the time to try it out. I'll be sure to revisit the scroll readers before merging, and I can post another update with additional changes/fixes as well

**Comment by retmas-gh** [comment]
Ah, yes, I've already checked these changes but did not want to impose so I was waiting haha.

The vertical mode does indeed look almost like I would expect it to.
The only thing I am perhaps uncertain about is the "width scaling" on a pc as it scales to 100% of the screen width not to the value of "Adjusted width" in Appearance setting I talked about before, but:
* since this setting is grayed out I'm not even sure if it's something that's taken in consideration anywhere at all (so it would be out of scope of this issue) or if it's only the changing part that's not ready yet
* I don't know how hard it would be to differentiate between a mobile and pc size because 100% scaling in case of a mobile screen is actually good
That said, the original scaling does work for the media I tested it with so it may just be a "nothingburger".

**Comment by aaronleopold** [comment]
> Ah, yes, I've already checked these changes but did not want to impose so I was waiting haha.

Haha not imposing at all

> The vertical mode does indeed look almost like I would expect it to.

Assuming it isn't what I have quoted below, what is different from what you would have expected? You can ignore if it's only what you pointed out below. 

> The only thing I am perhaps uncertain about is the "width scaling" on a pc as it scales to 100% of the screen width not to the value of "Adjusted width" in Appearance setting

Ah yeah, sorry I forgot to touch on it from your previous comment. The context around that setting is actually a bit interesting. The TLDR; is that is has nothing to do with the readers.

Originally, some folks expressed that they did not like having a sidebar and would prefer a topbar. I don't like topbars personally, but I added one as an option. Since there is no sidebar to anchor the screen when the topbar is selected, I also added a config to control the max width. The setting doesn't do anything for sidebar layout though, and is completely disconnected from the readers.

The readers are sort of like modal applications superimposed over the primary interface. I think if we wanted an artificial width constraint, it should be a different setting entirely (one specific to readers). I'm happy to add something like that so when you have width scaling selected you could then say "make the container around the image have a width 80% of the viewport" or something

**Comment by retmas-gh** [comment]
> Assuming it isn't what I have quoted below, what is different from what you would have expected? You can ignore if it's only what you pointed out below.

Sorry I was not more clear - the width scaling to 100% is the only thing I noticed.

> The TLDR; is that is has nothing to do with the readers.

Oh, sure, that clears it, thank you.

> (...) I'm happy to add something like that so when you have width scaling selected you could then say "make the container around the image have a width 80% of the viewport" or something

That would be a nice addition I think but it's not something requied to push this awesome change and can be added later or if someone would express such a need too, so you can close this issue with the linked PR.

Thank you for you work!

**Comment by aaronleopold** [comment]
This is going to go to nightly shortly as of https://github.com/stumpapp/stump/pull/453. I'm going to close this bug report, but if there are any glaring issues with the changes please feel free to re-open! If you have suggestions or more feedback kind of things, I ask that you just create a separate feature request to better isolate the ask 🙂
