### ISSUE TITLE
[FEATURE] OPDS v1.2 support for Cantook

### ISSUE THREAD

**Issue by n1ghthouse** [stumpapp/stump#447]
**Is your feature request related to a problem? Please describe.**
Unable to use OPDS v1.2 with Cantook as it would prefer auth encoded into the URL.

**Describe the solution you'd like**
Use v1.2 in a manner similar to Kavita. Generate OPDS URLs per user with auth encoded into them and also add support for covers.

**Additional context**
No

**Comment by aaronleopold** [comment]
I'll be implementing this alongside https://github.com/stumpapp/stump/issues/239 to unblock it
