### ISSUE TITLE
[FEATURE] Publish SVG and PSD Versions of App Icon

### ISSUE THREAD

**Issue by MatthewGlenn** [stumpapp/stump#478]
I would like to request that the maintainers publish SVG and PSD versions of the app icon. This would greatly assist with other projects and repositories that maintain lists of app icons. This request aligns with a related issue in the [dashboard icons](https://github.com/walkxcode/dashboard-icons/issues/733).

Having these files available would facilitate better integration and inclusion of the Stump app in homepage apps and other dashboard project. Thank you for considering this request!

**Comment by aaronleopold** [comment]
Hey 👋 I'm happy to upload an SVG of the icon. I would have to dig deep to find the original PSD though, so I can't promise that one will get added. As an aside, I'm curious why SVG over PNG/WebP?

> This request aligns with a related issue in the https://github.com/walkxcode/dashboard-icons/issues/733

Neat! Thanks for the context

**Comment by MatthewGlenn** [comment]
> Hey 👋 I'm happy to upload an SVG of the icon. I would have to dig deep to find the original PSD though, so I can't promise that one will get added. As an aside, I'm curious why SVG over PNG/WebP?
> 

For the PSD, I just asked for it because I thought it may be easier to make alternate icons in the future if it was available.
If it's a bunch of work to find the PSD, then the SVG alone would be fine. For **Dashboard-Icons**, they just want a PNG and SVG. You may need to ask the maintainer for more details, but I think they ask for SVG because it's easier to scale vector graphics than PNGs and WebP.
https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md

**Comment by aaronleopold** [comment]
I've put up an SVG image and will merge the [PR](https://github.com/stumpapp/stump/pull/479) in a moment. It will live in the `develop` branch until the next release 🙂
