### ISSUE TITLE
[BUG] Unable to find manual scan button

### ISSUE THREAD

**Issue by slavexe** [stumpapp/stump#488]
## Description of the Bug

Hi, according to the Libraries section of the documentation:

> To manually initiate a scan job, you can click the action button library selection menu on the sidebar and select "Scan". You may also navigate to the library's overview page and click the action button and select "Scan".

> For more thorough information on library scans, see the [filesystem scanning](https://www.stumpapp.dev/guides/filesystem-scans) guide.

However, I am not able to find any buttons that would allow me to manually scan a library.
In addition, clicking on the [filesystem scanning](https://www.stumpapp.dev/guides/filesystem-scans) link in the documentation goes to a page that does not exist.

## Expected Behavior

A button to manually scan a library should be present in the library overview page according to the documentation.

## To Reproduce

1. Go to library overview page
2. Scan button missing

**Environment:**

- OS: Linux

**Build Details:**

- Version: [v0.0.7](https://github.com/stumpapp/stump/releases/tag/v0.0.7)
- Docker: yes

**Comment by slavexe** [comment]
Is there any way to do a manual scan if a user has the primary topbar option selected in appearance settings? I now see the manual scan option after switching from topbar to sidebar, but I personally prefer the look of the topbar better. That would explain why I couldn't find that button before. Thanks for clarifying.

**Comment by aaronleopold** [comment]
> Is there any way to do a manual scan if a user has the primary topbar option selected in appearance settings?

Now that you mention it, I don't think there is! I've edited my previous checklist to include adding something there. The topbar is one of those things I added a while ago after being asked for it, but haven't had the time to revisit it.

No promises, but I'll aim to get some of these changes sometime before `0.0.10` is released
