### ISSUE TITLE
[BUG] Clean library button is not working

### ISSUE THREAD

**Issue by xendke** [stumpapp/stump#495]
## Description of the Bug

Clean library button shows the following error: `405 Method Not Allowed`

## Expected Behavior

Clean library button should remove all books in a library with missing files.

## To Reproduce

1. Go to Library Settings
2. Go to Deletion section
3. Click "Clean library" button

## Screenshots

![Screenshot 2024-11-02 143826](https://github.com/user-attachments/assets/d717e43b-917f-49e4-8a89-6005a5d5570d)

## Debugging Information

Looks like the Method should be PUT If I'm reading this right: [library.rs](https://github.com/stumpapp/stump/blob/experimental/apps/server/src/routers/api/v1/library.rs#L94).

Maybe [codegen](https://github.com/stumpapp/stump/blob/experimental/packages/sdk/src/controllers/library-api.ts#L183) for the sdk is not up to date?

From browser request:
```
Request URL: [REDACTED]/api/v1/libraries/08a2071e-ca65-47cf-8c2a-e27edbe367c4/clean
Request Method: POST
Status Code: 405 Method Not Allowed
Referrer Policy: strict-origin-when-cross-origin
```

**Environment:**

- OS: [Brave Browser]
- Device: [Android]

**Build Details:**

- Version: [experimental]
- Docker: [yes]

**Comment by aaronleopold** [comment]
Thanks for the bug report! Your write-up is very helpful, it is almost certainly a small, lingering regression from https://github.com/stumpapp/stump/pull/457.

I'll push up a fix either today or tomorrow and update this ticket once the experimental build is updated

**Comment by aaronleopold** [comment]
@xendke This should be fixed in the updated `experimental` build. I didn't have time to validate myself, but swapped out the request method to the correct one (PUT) so it should be good. If you are able to re-test, let me know and I can close this out afterwards

**Comment by xendke** [comment]
that did it, thanks @aaronleopold 🎉
