### ISSUE TITLE
Fix comic reader animation

### ISSUE THREAD

**Issue by aaronleopold** [stumpapp/stump#50]
Animation wasn’t really even complete, so not really a fix lol but the animation needs LOTS of tlc. I'm trying to mimic Panels animation

See `ImageBasedReader.tsx` -> AnimatedImageBasedReader

**Comment by hollisticated-horse** [comment]
What do you mean by Panels animation ?

**Comment by hollisticated-horse** [comment]
If you don't mind @aaronleopold, I like to go back and see old issues, to check if they are still a thing.

**Comment by aaronleopold** [comment]
Yeah of course, I don't mind at all
