### ISSUE TITLE
[BUG] Minified React error

### ISSUE THREAD

**Issue by Yur-ok** [stumpapp/stump#507]
## Description of the Bug

Just appears while using web interface (in Chrome)

## Screenshots

![image](https://github.com/user-attachments/assets/4b565e5c-5a67-4e49-a093-51bb30f97d6d)

## Debugging Information

Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

LOG
2024-11-15T06:27:08.533766225Z Adding group stump with gid 0
2024-11-15T06:27:08.539526564Z Adding user stump with uid 0
2024-11-15T06:27:08.534858893Z addgroup: gid '0' in use
2024-11-15T06:27:08.539583684Z adduser: unknown group stump

**Environment:**

- OS: [Linux]

**Build Details:**

- Version: [v0.0.7, Exact commit: 30bdb82, Build date October 12, 2024 3:38 AM]
- Docker: [yes]

**Comment by aaronleopold** [comment]
I'm closing this since there isn't much I can do without more info. If you or anyone else experiences this, feel free to comment here again and we can reopen it as needed.

**Comment by Yur-ok** [comment]
Hi @aaronleopold !
I was in vacation. 

So about extra info... I just can say that I got this error several times.
And I didn't nothin in my library from creation time.

Logs also are empty ((

I provide all info which could get in the first time.

So I'll try to dig as mush as I can!

**Comment by Yur-ok** [comment]
> If you refresh the page, does this error go away?

No


> If not, does clearing the cache make the error go away?

I'll try when it (if) it comes back and be sure to respond.
