### ISSUE TITLE
[BUG] OPDS Catalog Fails to Display

### ISSUE THREAD

**Issue by kulak** [stumpapp/stump#513]
## Description of the Bug

Open URL for OPDS.  Example: <http://10.0.1.4:1801/opds/v1.2/catalog>

HTML Response Body Contains Message:

> Wrong number of path arguments for `Path`. Expected 1 but got 0. Note that multiple parameters must be extracted with a tuple `Path<(_, _)>` or a struct `Path<YourParams>`

## Expected Behavior

Expected catalog content.

## To Reproduce

I used `podman` configuration pointing directly to v0.0.8.  I added discussion on this topic <https://github.com/stumpapp/stump/discussions/512>

```ini
# to run rootless on podman, put this is 
#     $USER/.config/containers/systemd/stump.container
# file and then run
#    systemctl --user daemon-reload
#    systemctl --user start stump.service

[Unit]

Description=stump

[Container]

Image=docker.io/aaronleopold/stump:0.0.8

UserNS=keep-id

# Volume Mapping: host:container:options
# host directories must exist and be owned by $USER
Volume=/data/Family/Books:/data:Z
Volume=/var/lib/family/.config/stump:/config:Z

# port mapping: host:container
PublishPort=1801:10801

# entry point script does too much, run directly
WorkingDir=/app
Entrypoint=/app/stump

[Service]

# https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Restart=
Restart=no

# Extend Timeout to allow time to pull the image
TimeoutStartSec=10

[Install]

# Start by default on boot, make sure to enable linger with 
#     loginctl enable-linger $USER
#
WantedBy=multi-user.target default.target
```

**Environment:**

- OS: Fedora 41
- Device: Firefox current version of browser on Fedora 41

**Build Details:**

- Version: 0.0.8, 
- Docker: yes, **podman**

Semantic version: [v0.0.8](https://github.com/stumpapp/stump/releases/tag/v0.0.8)
Exact commit: [2c0208c](https://github.com/stumpapp/stump/commit/2c0208c)
Build date: December 3, 2024 4:43 PM

**Comment by aaronleopold** [comment]
Thanks for bringing this to my attention! Unfortunate this slipped through the cracks for a few weeks that it sat in the `nightly` build, but happy it was eventually caught nonetheless. 

I've seemingly fixed it locally and pushed the changes up if you look at the linked PR. I've added a debug commit to push a `opds-path-error-patch` image through CI. It should be up [any minute](https://github.com/stumpapp/stump/actions/runs/12218390023/job/34083832228). If you can validate that corrects the issue on your end, I'll release a `0.0.9` tomorrow to patch the latest tag

**Comment by kulak** [comment]
> Thanks for bringing this to my attention! Unfortunate this slipped through the cracks for a few weeks that it sat in the `nightly` build, but happy it was eventually caught nonetheless.
> 
> I've seemingly fixed it locally and pushed the changes up if you look at the linked PR. I've added a debug commit to push a `opds-path-error-patch` image through CI. It should be up [any minute](https://github.com/stumpapp/stump/actions/runs/12218390023/job/34083832228). If you can validate that corrects the issue on your end, I'll release a `0.0.9` tomorrow to patch the latest tag

Is nightly docker image going to have the fix?

If it will, I can try it out.

**Comment by aaronleopold** [comment]
> It seems to work now

Awesome! Thanks for validating the image. I'll update this issue once the fix is fully released tomorrow

**Comment by aaronleopold** [comment]
The fix is in `nightly` and will make its way to latest once the [`0.0.9` build](https://github.com/stumpapp/stump/actions/runs/12224434536) completes
