### ISSUE TITLE
[BUG] 404 for OPDS Catalog if AppKey is generated

### ISSUE THREAD

**Issue by kulak** [stumpapp/stump#516]
## Description of the Bug

OPDS links return 404 after App key is generated.  The 404 status is returned regardless of link style used:

- [with app key](http://10.0.1.4:1801/opds/stump_my_app_key_V9/v1.2/catalog)
- [without app key](http://10.0.1.4:1801/opds/v1.2/catalog/)

## Expected Behavior

XML catalog content.

## To Reproduce

Setup follows instructions in [issue 513](https://github.com/stumpapp/stump/issues/513).
Use docker `Image=docker.io/aaronleopold/stump:opds-path-error-patch`.

Generate key with settings:

```
Name: OPDS Access
Permissions: file:download, library:scan
Expiration: Never
Last used: Never
Created: December 7, 2024 10:56 PM
```

## Screenshots

The following screenshot is of network traffic for "with app key" link, network traffic is set to persisted:

![image](https://github.com/user-attachments/assets/ac494062-e5fc-4443-b873-b904b34458d8)

## Debugging Information

**Environment:**

- OS: Fedora 41, latest Firefox on Fedora

**Build Details:**

- Version: opds-path-error-patch
- Docker: yes, podman

**Comment by aaronleopold** [comment]
The fix is in `nightly` and will make its way to latest once the [`0.0.9` build](https://github.com/stumpapp/stump/actions/runs/12224434536) completes

**Comment by kulak** [comment]
Docker image 0.0.9 works with app key and without app key using browser authentication prompt.
