### ISSUE TITLE
[BUG] Fails to build on nixos

### ISSUE THREAD

**Issue by Lyamc** [stumpapp/stump#517]
## Description of the Bug

Here's the output from `nixos-rebuild switch`

```
warning: creating lock file '/etc/nixos/flake.lock':
• Added input 'flake-utils':
    'github:numtide/flake-utils/11707dc2f618dd54ca8739b309ec4fc024de578b?narHash=sha256-l0KFg5HjrsfsO/JpG%2Br7fRrqm12kzFHyUHqHCVpMMbI%3D' (2024-11-13)
• Added input 'flake-utils/systems':
    'github:nix-systems/default/da67096a3b9bf56a91d16901293e51ba5b49a27e?narHash=sha256-Vy1rq5AaRuLzOxct8nz4T6wlgyUR7zLU309k9mBC768%3D' (2023-04-09)
• Added input 'nixpkgs':
    'github:NixOS/nixpkgs/929116e316068c7318c54eb4d827f7d9756d5e9c?narHash=sha256-aLJxoTDDSqB%2B/3orsulE6/qdlX6MzDLIITLZqdgMpqo%3D' (2024-12-05)
• Added input 'rust-overlay':
    'github:oxalica/rust-overlay/430c8b054e45ea44fd2c9521a378306ada507a6c?narHash=sha256-tIML2axjm4AnlKP29upVJxzBpj4Cy4ak%2BPKonqQtXmc%3D' (2024-12-08)
• Added input 'rust-overlay/nixpkgs':
    'github:NixOS/nixpkgs/b69de56fac8c2b6f8fd27f2eca01dcda8e0a4221?narHash=sha256-f0SBJz1eZ2yOuKUr5CA9BHULGXVSn6miBuUWdTyhUhU%3D' (2024-10-10)
error: flake 'path:/etc/nixos' does not provide attribute 'packages.x86_64-linux.nixosConfigurations."nixos".config.system.build.nixos-rebuild', 'legacyPackages.x86_64-linux.nixosConfigurations."nixos".config.system.build.nixos-rebuild' or 'nixosConfigurations."nixos".config.system.build.nixos-rebuild'
```

Note that "nixos" is the hostname

## Expected Behavior

Successful build

## To Reproduce

```
sudo su
cd /etc/nixos
wget https://raw.githubusercontent.com/stumpapp/stump/refs/heads/main/flake.nix
sudo nixos-rebuild switch
```

**Environment:**

- OS: NixOS 24.11.710315.b681065d0919 (Vicuna)

**Additional context**

Not really sure if I'm doing this right btw.

**Comment by aaronleopold** [comment]
> Not really sure if I'm doing this right btw

Me neither 😅 The nix support was added about [a year ago](https://github.com/stumpapp/stump/commit/f8e3dfcd152c2c8ed7bd86cdf0320eaa6b810dd9) by a contributor and I honestly don't use nix enough to say what might be wrong here.

@f8thl3ss idk if you might have a clue since you originally added the nix stuff, but I'll try to look into it sometime within the next few weeks

**Comment by aaronleopold** [comment]
FWIW the nix CI check passed with the latest release 👀 https://github.com/stumpapp/stump/actions/runs/12225531695/job/34099625825

**Comment by Lyamc** [comment]
Ah, I figured it out. That flake is meant for a development shell. Nevermind!
