### ISSUE TITLE
[BUG] Thumbnails failed to generate

### ISSUE THREAD

**Issue by hucurve** [stumpapp/stump#532]
have a library with a large number of files,stump scaner is very fast and I am very happy with it
but when I tried to resize the thumbnails to reduce the congestion on the page 
I found that the thumbnail generation function only worked correctly for about ten seconds and then paused 
(I checked the thumbnail folder to make sure it was paused) 
The only way to keep running for ten seconds is to re-scan, and then pause again
thats really annoying~
![image](https://github.com/user-attachments/assets/550b310b-e5d8-473f-9688-fef2642312b9)

**Comment by hucurve** [comment]
But neither the Docker nor the software displays any logs. Can you help me find them in the specific file?
![image](https://github.com/user-attachments/assets/7c2f1969-dcec-4cbe-a59e-7984032ec4d3)
![image](https://github.com/user-attachments/assets/52e65563-c97a-425a-942d-ceb156bb5479)

**Comment by aaronleopold** [comment]
You'll need to adjust the config to change the log level: https://www.stumpapp.dev/guides/configuration/server-options#stump_verbosity

I'd suggest setting it to 3 while you're debugging, then once you have the logs you need turn it down to either 1 or 0 for everyday use

**Comment by hucurve** [comment]
Thanks for the guidance! The first and second runs of this log, both thumbnail generation process were stopped quickly!
[2nd run Stump.log](https://github.com/user-attachments/files/18219477/2nd.run.Stump.log)
[1st run Stump.log](https://github.com/user-attachments/files/18219478/1st.run.Stump.log)

**Comment by aaronleopold** [comment]
Thank you! I'm not by a computer to really thoroughly look through the logs, but they should be helpful.

Once it reaches a point where it doesn't progress, how long until you cancel the job? It's a much more time consuming and CPU-intensive task than a scan, so it is very expected to take more time. 

From the cursory glance I took at the logs on my phone, you have the default concurrency of 50 images at once. This means 50 images will be loaded, downscaled (according to your config), and converted in memory in parallel before being written to disk. If you want, there is also a setting you can try adjusting to lower the number of files it processes at once: https://www.stumpapp.dev/guides/configuration/server-options#stump_max_thumbnail_concurrency

**Comment by hucurve** [comment]
OMG，it works
![image](https://github.com/user-attachments/assets/ff2dc82a-9fa2-40dc-b2af-4b31443eb39f)
Lowering this value solves the problem! Is my computer not good enough?
I used AMD Ryzen 7 5700G with Radeon Graphics    3.80 GHz +64G RAM

**Comment by JMicheli** [comment]
A little surprising to me that it fails for higher concurrency values. There may be something worth investigating there.

**Comment by aaronleopold** [comment]
Woohoo 🎉 Happy that did the trick!

> Lowering this value solves the problem! Is my computer not good enough? ...AMD Ryzen 7 5700G with Radeon Graphics 3.80 GHz +64G RAM

That's more than enough in general, without seeing a memory profile of what exactly went wrong I'd guess that 50 high res images + 50 downscaled converted copies is just a memory hog. I'll consider lowering the default value.

**Comment by aaronleopold** [comment]
> A little surprising to me that it fails for higher concurrency values. There may be something worth investigating there.

I'm hesitant to call it failing until I hear how long before giving up and cancelling the job, but yes totally agree that it's worth exploring. I'd be curious to see how the 50 threads + over 50*2 buffered images in memory plays into it
