### ISSUE TITLE
[BUG] "STUMP_ALLOWED_ORIGINS" wildcard causes infinite restarts

### ISSUE THREAD

**Issue by vorpalhex** [stumpapp/stump#537]
```
thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-http-0.5.2/src/cors/allow_origin.rs:55:13:
Wildcard origin (`*`) cannot be passed to `AllowOrigin::list`. Use `AllowOrigin::any()` instead
note
```

This happened because I added `*` as an entry to `STUMP_ALLOWED_ORIGINS` on the docker image. This caused that origin to be written to the Stump.toml, which then resulted in Stump not booting even after it was removed from the env (because it was still in the toml due to how origins are added)

Possible fixes:
1. Just reject/ignore `*` in the STUMP_ALLOWED_ORIGINS. Quick fix that does actually resolve the problem. 
2. Detect `*` in STUMP_ALLOWED_ORIGINS, update logic to be `AllowOrigin::any()`.

**Comment by JMicheli** [comment]
Good catch, I'll get a PR up for this one shortly. I favor solution 2 above at first blush.

**Comment by aaronleopold** [comment]
@JMicheli's fix has made its way into the `nightly` image, so I'll close this issue. If using a wildcard still presents some kind of issue, we can re-open this and figure it out
