### ISSUE TITLE
Support markdown descriptions

### ISSUE THREAD

**Issue by aaronleopold** [stumpapp/stump#67]
One of my test files has markdown and I never noticed. I think it would be a really nice feature to allow for rendering and editing media descriptions as markdown. 

Will consider this for all entities with description fields.

**Comment by dancamdev** [comment]
Let's do it - is the test file in the source code already? If not, mind sharing it?

**Comment by aaronleopold** [comment]
This will be added alongside the filter and sort changes I am currently working on: https://github.com/stumpapp/stump/tree/al/filter-and-sort
